window.GardenContent = window.GardenContent || {};

// Grounding links (plan §13.11). Free, no-signup, no-setup; re-verified each release.
window.GardenContent.groundingLinks = [
  { id: "abc-news-24-live", title: "ABC News 24 (live)", kind: "stream",
    url: "https://www.youtube.com/watch?v=gC4DWVF1O6E",
    why: "Put the news on in the background if it's too hard to watch directly — it eases the loneliness and gently pulls you out of your own bubble." },
  { id: "iss-live", title: "Earth from the ISS (live)", kind: "cam",
    url: "https://www.youtube.com/watch?v=21X5lGlDOfg",
    why: "Slow, silent, perspective-shifting." },
  { id: "lofi-beats-stream", title: "Lo-fi beats to relax to (live)", kind: "stream",
    url: "https://www.youtube.com/watch?v=jfKfPfyJRdk",
    why: "Soft, steady company." },
  { id: "rainy-mood", title: "Rainy Mood", kind: "site",
    url: "https://www.rainymood.com/",
    why: "A one-tap rain soundscape. Instant ambient calm, no signup." },
  { id: "a-soft-murmur", title: "A Soft Murmur", kind: "site",
    url: "https://asoftmurmur.com/",
    why: "A free ambient mixer (rain, wind, fire, waves). Build your own calm; no signup." },
  { id: "mynoise", title: "myNoise", kind: "site",
    url: "https://mynoise.net/",
    why: "A free soundscapes library (rain, singing bowls, drones). Deep grounding textures; no signup." },
  { id: "radio-garden", title: "Radio Garden", kind: "site",
    url: "https://radio.garden/",
    why: "Tune into live radio from anywhere on Earth. A window out of the bubble; feels less lonely." },
  { id: "drive-and-listen", title: "Drive & Listen", kind: "site",
    url: "https://driveandlisten.herokuapp.com/",
    why: "Drive through a city with its ambient street sound + local radio. Gentle motion and company; no signup." },
  { id: "monterey-sea-otters", title: "Monterey Bay sea otters (live)", kind: "cam",
    url: "https://www.youtube.com/watch?v=O-FTtf6PeqQ",
    why: "Gentle, living, low demand." },
  { id: "monterey-jellies", title: "Monterey Bay jellyfish (live)", kind: "cam",
    url: "https://www.youtube.com/watch?v=25Sjgg4-qYg",
    why: "Hypnotic and calming." },
  { id: "explore-org-nature-cams", title: "explore.org nature cams", kind: "cam",
    url: "https://explore.org/",
    why: "Live nature cams (bears at a river, and more). Free, no signup, quietly alive." },
  { id: "window-swap", title: "Window Swap", kind: "site",
    url: "https://www.window-swap.com/",
    why: "A random real window somewhere in the world with its sounds. A small, foreign moment of company." },
  { id: "smithsonian-zoo-cams", title: "Smithsonian National Zoo cams", kind: "cam",
    url: "https://nationalzoo.si.edu/webcams",
    why: "Live animal cams. Free, no signup, soft focus." },
  { id: "virtual-fireplace", title: "A virtual fireplace", kind: "video",
    url: "https://www.youtube.com/watch?v=L_LUpnjgPso",
    why: "A long fireplace + crackle video. Warm, zero demand." }
];
