window.GardenContent = window.GardenContent || {};

// Recognise moments — short lines a mum may recognise from her own week
// (the painful patterns of the system, and the quiet acts of love).
// Seeded from the original solidarity cards (plan §13.4).
window.GardenContent.recogniseMoments = {
  survivor: [
    "Family report says dad is 'protective' despite your AVO",
    "ICL hasn't met your child yet",
    "Accused of 'parental alienation' for asking about school",
    "Kids parrot dad's phrases word-for-word",
    "Handover at a police station carpark",
    "Court adjourned. Again.",
    "Ex breaches parenting orders — no consequence",
    "You get enforcement action for one missed call",
    "FDR mediator: 'You just need to communicate better'",
    "Supervised visits — that you pay for",
    "Child refuses contact — court blames you",
    "His lawyer costs more than your annual rent",
    "Legal Aid funding runs out mid-case",
    "School calls dad first despite your orders",
    "Ex posts 'happy family' pics while you haven't seen the kids in months",
    "Police: 'That's a family law matter'",
    "65DAA lawyer letter lands at 5pm Friday",
    "Psychologist report funded entirely by his side",
    "Gatekeeping label for setting basic boundaries",
    "He told the kids you're 'unstable' or 'dangerous'",
    "Medical info withheld — 'privacy'",
    "'Best interests of the child' cited against you",
    "Email asking about homework = 'harassment'",
    "Changeover anxiety every single week",
    "Document everything — you already have 47 folders",
    "Kids return repeating his version of events",
    "Centrelink questions you while he hides income",
    "His new partner is now 'primary carer'",
    "Court accepts child's wishes after 18 months of alienation",
    "Safe Steps / DV helpline becomes your second home",
    "Ex uses child support as a weapon",
    "Family report writer spoke to him twice, you once",
    "You cry in the car after every court date",
    "Support group nod — they all know that look",
    "Mention coercive control — blank stares in the courtroom"
  ],
  ledger: [
    "Wrote a letter to your kids — kept safe for when they're ready",
    "Logged an entry in your connection diary",
    "Liaised with school about something that matters",
    "Spoke with a counsellor about your child's wellbeing",
    "Created social media your kids might find you on someday",
    "Researched something they're into — just to feel closer",
    "Sent a prayer, thought, or wish to them before sleep",
    "Responded to a hostile email in BIFF style",
    "Negotiated make-up time in good faith",
    "Agreed to supervised visits to keep the door open",
    "Showed love when faced with difficult behaviour",
    "Turned up to an event even when you were shamed",
    "Corrected a professional's false narrative — calmly, in writing",
    "Didn't rise to the bait this time",
    "Saved a birthday message they'll read one day",
    "Attended handover when every part of you wanted to hide",
    "Asked the ICL something constructive about your child",
    "Left a trail — updated contact details, hope intact",
    "Remembered a detail only a mum would know",
    "Celebrated their birthday quietly, but fully",
    "Recorded a voice message for the future",
    "Maintained boundaries without abandoning connection",
    "Checked in with another mum who gets it",
    "Shared a tip or resource in the group",
    "Listened to someone without trying to fix them",
    "Sent a 🤍 to a mum having a hard day",
    "Showed up to a course session — even exhausted",
    "Saw your counsellor this week",
    "Had coffee with a friend who sees you",
    "Went for a walk when grief hit hard",
    "Started a hobby that's just for you",
    "Slept when your body needed it — guilt-free",
    "Let yourself laugh today",
    "Journalled without editing yourself",
    "Said no to something that drained you",
    "Cried, then got back up",
    "Read something that helped you breathe",
    "Moved your body — gently counts",
    "Made yourself a proper meal",
    "Sat in nature for ten minutes",
    "Named one thing you're proud of today",
    "Forgave yourself for not being perfect"
  ]
};
